services:
  app:
    image: gcn-mgmt:latest
    privileged: true
    pid: "host"
    restart: unless-stopped
    ports:
      - "8080:8000"
    volumes:
      - ./data:/data # Mount-Pfad zur Datenbank
      - ./logs:/app/logs # Log-Dateien werden im Container abgelegt
      - /var/run/docker.sock:/var/run/docker.sock # Zugriff auf den Docker-Daemon
      - /opt/gridcal:/opt/gridcal
    environment:
      - BACKEND_CONTAINER_NAME=fastapi-test-backend-1
      - DB_PATH=/data/gcn.db
      - ADMIN_USER=user
      - ADMIN_PASS=pass
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    image: alpine:latest
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    ports:
      - "8081:8081"
    environment:
      - MOCK_MODE=true
