services:
  app:
    # build: .
    image: gcn-mgmt:latest
    privileged: true
    ports:
      - "8080:8000"
    volumes:
      - ./data:/data # Mount-Pfad zur Datenbank
      - ./logs:/app/logs # Log-Dateien werden im Container abgelegt
      - /var/run/docker.sock:/var/run/docker.sock # Zugriff auf den Docker-Daemon
    environment:
      - BACKEND_CONTAINER_NAME=fastapi-test-backend-1
      - DB_PATH=/data/gcn.db
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    image: alpine:latest
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    ports:
      - "8081:8081"
    environment:
      - MOCK_MODE=true
