services:
  gc-admin:
    image: gc-admin:latest
    build: .
    privileged: true
    pid: "host"
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./mock/opt/gridcal:/opt/gridcal
      - /etc/localtime:/etc/localtime:ro
    environment:
      - BACKEND_CONTAINER_NAME=fastapi-test-backend-1
      - DB_PATH=/data/gcn.db
      - ADMIN_USER=user
      - ADMIN_PASS=pass
      - TZ=Europe/Berlin
      - MOCK_MODE=True
      - DEBUG=True
    env_file:
      - .env
    depends_on:
      - backend

  frontend:
    build:
      context: ./mock
      dockerfile: Dockerfile-MockLog
    labels:
      Version: "1.0.1"

  gatewaycontrol:
    build:
      context: ./mock
      dockerfile: Dockerfile-MockLog
    labels:
      Version: "1.0.2"

  backend:
    build:
      context: ./mock
      dockerfile: Dockerfile-MockLog
    labels:
      Version: "1.0.3"

  gcfcs:
    build:
      context: ./mock
      dockerfile: Dockerfile-MockLog
    labels:
      Version: "1.0.4"

  gcgw:
    build:
      context: ./mock
      dockerfile: Dockerfile-MockLog
    labels:
      Version: "1.0.5"

  gcnia:
    build:
      context: ./mock
      dockerfile: Dockerfile-MockLog
    labels:
      Version: "1.0.6"