services:
  app:
    image: gcn-mgmt:latest
    build: .
    privileged: true
    pid: "host"
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./data:/data # Mount-Pfad zur Datenbank
      - ./logs:/app/logs # Log-Dateien werden im Container abgelegt
      - /var/run/docker.sock:/var/run/docker.sock # Zugriff auf den Docker-Daemon
      - ./mock/opt/gridcal:/opt/gridcal
      - /etc/localtime:/etc/localtime:ro
    environment:
      - BACKEND_CONTAINER_NAME=fastapi-test-backend-1
      - DB_PATH=/data/gcn.db
      - ADMIN_USER=user
      - ADMIN_PASS=pass
      - TZ=Europe/Berlin
      - MOCK_MODE=True
    env_file:
      - .env
    depends_on:
      - backend

  frontend:
    image: alpine:latest
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    labels:
      Version: "1.0.1"
  
  gatewaycontrol:
    image: alpine:latest
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    labels:
      Version: "1.0.2"
  
  backend:
    image: alpine:latest
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    labels:
      Version: "1.0.3"
  
  gcfcs:
    image: alpine:latest
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    labels:
      Version: "1.0.4"
  
  gcgw:
    image: alpine:latest
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    labels:
      Version: "1.0.5"
  
  gcnia:
    image: alpine:latest
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    labels:
      Version: "1.0.6"