services:
  app:
    image: gcn-mgmt-armv7:latest
    privileged: true
    pid: "host"
    restart: unless-stopped
    ports:
      - "8080:8000"
    volumes:
      - /media/sd/gridcal/data:/data
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/gridcal:/opt/gridcal
    environment:
      - BACKEND_CONTAINER_NAME=gridcal-backend-1
      - DB_PATH=/data/gcn.db
      - ADMIN_USER=user
      - ADMIN_PASS=pass
    env_file:
      - .env